#!/bin/sh
# Starts streaming to Twitch.

. "$( dirname "$0" )/../settings.sh"
. "$shldir/tests.sh"

stream="${streamuri}${streamkey}"
display=0.0 # which display to stream
framerate=30

capture_x=0 # capture offset from left of screen
capture_y=45 # capture offset from top of screen

dimensions_x=256
dimensions_y=240

get_audio_args() {
    if test_readable_file "$audiosrc"; then
        # use audio from file
        echo "-i $audiosrc -c:a copy -ar 44100 -ac 2"
    elif [ "$audiosrc" -eq $gameaudio ]; then
        # use audio from game
        echo "-thread_queue_size 64 -f pulse -ar 44100 -i default"
    fi
}

send_alarm() {
    # sends alarm to bot proces
    bot_pid=$( cat "$datadir/procs/bot.py.id" 2>/dev/null )
    [ -n "$bot_pid" ] && kill -s ALRM "$bot_pid"
}

die() {
    echo "Exiting stream script"
    kill 0
}

trap "exit" INT TERM
trap "die" EXIT

while :; do
    ffmpeg \
        $(get_audio_args) \
        -threads 4 -f x11grab -r $framerate -s ${dimensions_x}x${dimensions_y} -i :${display}+${capture_x},${capture_y} \
        -c:v libx264 -preset medium -pix_fmt yuv420p \
        -shortest -f avi "$stream" 2>&1 |\
            tee -a "$(get_log_dest stream.log)"

    if $streamloops; then
        $streamsig && send_alarm
    else
        exit 0
    fi
done
