#!/bin/sh
# Starts streaming to Twitch.

. "$( dirname "$0" )/../settings.sh"
. "$shldir/tests.sh"

load_stream_vars
stream="${s_uri}${s_dest}"

get_audio_args() {
    case $s_audio_type in
        $fileaudio)
            if test_readable_file "$s_audio_file"; then
                echo "-i $s_audio_file -c:a mp3 -ac 2"
            else
                set_data s_audio_type $noaudio >/dev/null
            fi
            ;;
        $gameaudio)
            echo "-thread_queue_size 64 -f pulse -ar 44100 -i default"
            ;;
    esac
}

send_signal() {
    bot_pid=$( cat "$datadir/proc/bot.py.id" 2>/dev/null )
    echo "Sending signal to bot with PID $bot_pid"
    [ -n "$bot_pid" ] && kill -s ALRM "$bot_pid"
}

die() {
    echo "Exiting stream script"
    kill 0
}

trap "exit" INT TERM
trap "die" EXIT

while :; do
    ffmpeg \
        $(get_audio_args) \
        -threads 4 -f x11grab -r $s_framerate -s ${s_dimensions_x}x${s_dimensions_y} -i :${s_display}.${s_screen}+${s_capture_x},${s_capture_y} \
        -c:v libx264 -preset medium -pix_fmt yuv420p \
        -shortest -f flv "$stream" 2>&1 |\
            tee -a "$(get_log_dest stream.log)"

    if $s_loops; then
        $s_sig && send_signal
    else
        exit 0
    fi
done
