#!/bin/sh

# for storing project data
for d in bot shell; do
    mkdir -p ~/.twitch-plays-pi/$d
done

basedata=~/.twitch-plays-pi/shell/basedir.dat
! [ -e "$basedata" ] && echo "$(pwd)" > "$basedata" # bootstrap basedir data file
unset basedata

cd "$( dirname $0 )" # in case script is ran from a different directory

. shell/utils/tests.sh

if test_empty "$(which whiptail)"; then
    echo "Error: Whiptail must be installed to run config.sh" >&2
    exit 1
fi

. shell/settings.sh
. shell/menu/main.sh

main_menu
