#!/bin/sh

cd "$( dirname "$0" )" # in case script is ran from a different directory

mkdirs_if_absent() {
    for path in $@; do
        mkdir -p "$path"
    done
}

# for storing project data
datadir=~/.twitch-plays-pi/
basedata="$datadir/shell/basedir.dat"

# initializing project data if needed
mkdirs_if_absent "$datadir/bot" "$datadir/shell" "$datadir/proc"
[ ! -e "$basedata" ] && echo "$(pwd)" >"$basedata"

# portable version of "if ! which whiptail >/dev/null"
if which whiptail >/dev/null; then :; else
    echo "Error: Whiptail must be installed to run config.sh" >&2
    exit 1
fi

. shell/menu/main.sh
main_menu
