#!/bin/sh
# Runs the 3 twitch-plays scripts concurrently. Configurable options are listed in the help command.

cd "$( dirname "$0" )"

. shell/tests.sh

# script flags
bot=1
nes=2
stream=4

# PIDs
botid=
nesid=
streamid=

# relevant paths
datadir=~/.twitch-plays-pi/proc/
scriptdir="shell/core/"
outdest=/dev/null       # destination of script output

scripts=0               # mask of scripts to run; if 0, all will run
dryrun=false            # whether or not to actually execute the target scripts

get_flag() {
    # $1: Flag to check mask for
    # returns success if flag found or $scripts is 0, otherwise fails

    [ "$(( $scripts & $1 ))" -eq $1 ] 2>/dev/null || [ $scripts -eq 0 ]
}

start_script() {
    # calls script in $scriptdir with name $1, saving
    # the PID in case something goes wrong

    # $1: script name

    echo "Starting $1 script..."
    "$scriptdir/$1" >$outdest 2>&1 &
    echo $! >"$datadir/$1.id"
    eval "${1}id=$!"
    wait
}

die() {
    kill 0
}

while getopts "hvbnsd" opt; do
    case $opt in
        h)
            # whitespace type is important here
            # leading tabs are ignored but not leading spaces
            cat <<-EOF
			Usage: ./run.sh [-h] [-bns] [-q] [-d]
			Options:
			    -h      Show this help message and exit.
			    -b      Start the bot script.
			    -n      Start the NES script.
			    -s      Start the streaming script.
			    -v      Don't suppress script outputs (verbose).
			    -d      Debug (don't execute core scripts, dump status).

			If any of [-bns] are used, only the specified scripts will run.
			Otherwise, all scripts will run.
			EOF

            exit 0
            ;;
        v)
            outdest=/dev/stdout
            ;;
        b)
            scripts=$((scripts | bot))
            ;;
        n)
            scripts=$((scripts | nes))
            ;;
        s)
            scripts=$((scripts | stream))
            ;;
        d)
            dryrun=true
            ;;
    esac
done

if $dryrun; then
    echo "Output destination: $outdest"
    echo "Enabled scripts:"
    get_flag $bot && printf "\t* Bot\n"
    get_flag $nes && printf "\t* NES\n"
    get_flag $stream && printf "\t* Stream\n"
    exit 0
fi

trap "exit" INT TERM
trap "die" EXIT

# run each script indicated by flags in $scripts.
# PIDs are saved in $datadir/{name}.id if manual killing necessary

get_flag $bot && start_script bot &
get_flag $nes && start_script nes &
get_flag $stream && start_script stream &

printf "Press ^C to stop processes\n\n"
wait
